import { profile } from '../data/profile'

/**
 * Sumit's actual professional headshot, served locally as pre-sized WebP with
 * a JPEG fallback (generated by scripts/gen-profile-image.mjs). The largest
 * asset is under 6 kB, so it costs nothing to make it eager and high-priority
 * in the hero — it sits above the fold and would otherwise cause a late shift.
 */
type Props = {
  /** Rendered diameter in CSS pixels. Drives the srcset sizes hint. */
  size: number
  className?: string
  /** Hero usage: load eagerly and decorate with a ring. */
  priority?: boolean
  /**
   * Override the alt text. Pass "" where adjacent text already names the
   * element (the nav and footer links), so screen readers do not hear the
   * name twice.
   */
  alt?: string
}

export function Avatar({ size, className = '', priority = false, alt }: Props) {
  return (
    <picture>
      <source
        type="image/webp"
        srcSet="/profile/profile-96.webp 96w, /profile/profile-176.webp 176w, /profile/profile-264.webp 264w"
        sizes={`${size}px`}
      />
      <img
        src="/profile/profile-176.jpg"
        srcSet="/profile/profile-96.jpg 96w, /profile/profile-176.jpg 176w, /profile/profile-264.jpg 264w"
        sizes={`${size}px`}
        width={size}
        height={size}
        alt={alt ?? `${profile.name}, ${profile.role}`}
        loading={priority ? 'eager' : 'lazy'}
        decoding={priority ? 'sync' : 'async'}
        fetchPriority={priority ? 'high' : 'auto'}
        className={`rounded-full object-cover object-top ${className}`}
        style={{ width: size, height: size }}
      />
    </picture>
  )
}
