/**
 * Generates src/data/techIcons.ts containing ONLY the brand icon paths this site
 * uses, pulled from the `simple-icons` package at build time. This keeps real
 * vendor marks without shipping the whole icon library to the browser.
 *
 * Each icon also gets theme-adjusted colours. Several brand colours sit close to
 * black (GitHub #181717, OWASP #000000) and vanish on a dark background; others
 * are near-white and vanish on a light one. We nudge lightness into a readable
 * band per theme while keeping the hue, so marks stay recognisable and legible.
 *
 * Run: npm run icons
 */
import { writeFileSync } from 'node:fs'
import * as si from 'simple-icons'

const SLUGS = [
  'javascript', 'openjdk', 'python', 'php', 'mysql', 'terraform', 'gnubash',
  'html5', 'css', 'nodedotjs', 'express', 'laravel', 'django', 'mongoose',
  'jsonwebtokens', 'ejs', 'chartdotjs', 'bootstrap', 'mongodb',
  'linkedin', 'gmail',
  'googlecloud', 'jenkins', 'docker', 'kubernetes', 'argo', 'githubactions',
  'git', 'github', 'nginx', 'linux', 'sonarqubeserver', 'trivy', 'owasp',
  'prometheus', 'grafana', 'letsencrypt', 'kalilinux', 'cisco',
]

/* ----------------------------------------------------------- colour helpers */

const hexToRgb = (h) => [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16))
const rgbToHex = (r, g, b) =>
  [r, g, b]
    .map((v) => Math.round(Math.max(0, Math.min(255, v))).toString(16).padStart(2, '0'))
    .join('')

/** WCAG relative luminance, 0 (black) to 1 (white). */
function luminance(hex) {
  const [r, g, b] = hexToRgb(hex).map((v) => {
    const c = v / 255
    return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4
  })
  return 0.2126 * r + 0.7152 * g + 0.0722 * b
}

function rgbToHsl(r, g, b) {
  r /= 255
  g /= 255
  b /= 255
  const max = Math.max(r, g, b)
  const min = Math.min(r, g, b)
  const l = (max + min) / 2
  if (max === min) return [0, 0, l]
  const d = max - min
  const s = l > 0.5 ? d / (2 - max - min) : d / (max + min)
  let h
  if (max === r) h = ((g - b) / d + (g < b ? 6 : 0)) / 6
  else if (max === g) h = ((b - r) / d + 2) / 6
  else h = ((r - g) / d + 4) / 6
  return [h, s, l]
}

function hslToRgb(h, s, l) {
  if (s === 0) return [l * 255, l * 255, l * 255]
  const q = l < 0.5 ? l * (1 + s) : l + s - l * s
  const p = 2 * l - q
  const f = (t) => {
    if (t < 0) t += 1
    if (t > 1) t -= 1
    if (t < 1 / 6) return p + (q - p) * 6 * t
    if (t < 1 / 2) return q
    if (t < 2 / 3) return p + (q - p) * (2 / 3 - t) * 6
    return p
  }
  return [f(h + 1 / 3) * 255, f(h) * 255, f(h - 1 / 3) * 255]
}

const setLightness = (hex, l) => {
  const [h, s] = rgbToHsl(...hexToRgb(hex))
  return rgbToHex(...hslToRgb(h, s, l))
}

/** Readable on the dark surface (#0e121b). */
function forDark(hex) {
  if (luminance(hex) >= 0.16) return hex
  const [, s] = rgbToHsl(...hexToRgb(hex))
  // Near-greyscale brands (GitHub, OWASP) have no hue worth preserving.
  if (s < 0.12) return 'c6cddb'
  return setLightness(hex, 0.64)
}

/** Readable on the light surface (#ffffff). */
function forLight(hex) {
  if (luminance(hex) <= 0.62) return hex
  const [, s] = rgbToHsl(...hexToRgb(hex))
  if (s < 0.12) return '4b5466'
  return setLightness(hex, 0.42)
}

/* ------------------------------------------------------------------ generate */

const toKey = (s) => 'si' + s.charAt(0).toUpperCase() + s.slice(1)

const found = {}
const missing = []
for (const slug of SLUGS) {
  const icon = si[toKey(slug)]
  if (icon?.path) {
    found[slug] = {
      title: icon.title,
      light: forLight(icon.hex),
      dark: forDark(icon.hex),
      path: icon.path,
    }
  } else missing.push(slug)
}

const body = Object.entries(found)
  .map(
    ([slug, v]) =>
      `  ${slug}: { title: ${JSON.stringify(v.title)}, light: '#${v.light}', dark: '#${v.dark}', path: ${JSON.stringify(v.path)} },`,
  )
  .join('\n')

writeFileSync(
  new URL('../src/data/techIcons.ts', import.meta.url),
  `// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.\n` +
    `// Brand marks from simple-icons, trimmed to only what this site renders,\n` +
    `// with per-theme colours adjusted for contrast.\n\n` +
    `export type TechIcon = { title: string; light: string; dark: string; path: string }\n\n` +
    `export const techIcons: Record<string, TechIcon> = {\n${body}\n}\n`,
)

console.log(`wrote ${Object.keys(found).length} icons`)
if (missing.length) console.log(`MISSING (no simple-icons entry): ${missing.join(', ')}`)
